---
title: "Viz"
format: html
editor: visual
---



```{r, include = F}
library(tidyverse)
library(lubridate)
```


```{r bobsog}

burgers <- data.frame(employee=c("Bob", "Gene",
                              "Linda", "Louise",
                              "Tina"),
                   time=c(25, 30, 60, 20, 50),
                   age=c(42, 11, 39, 9, 13),
                   interest=c("cooking", "music", "wine", "chaos", "horses"))

burgers

burgers <- burgers |> 
  mutate(where="front")

burgers
```

```{r bobs, warning=F, message=F, include=F, fig.height=3}
burgers

ggplot(burgers, aes(x=where, y=time, fill=employee)) + 
  geom_col(position="stack") 
```


```{r bobs2, warning=F, message=F, include=F, fig.height=3}
burgers

ggplot(burgers, aes(x=employee, y=time, fill=employee)) + 
  geom_col(position="stack")
```

```{r bobs3a, warning=F, message=F}
  ggplot(burgers) + 
    geom_point(aes(x=employee, y=time))
```

```{r bobs3b, warning=F, message=F}
  ggplot(burgers) + 
    geom_point(aes(x=employee, y=time, fill=employee))
```


```{r bobs3c, warning=F, message=F}
  ggplot(burgers) + 
    geom_point(aes(x=employee, y=time, fill=employee, color=employee)) #ROTATE 
    geom_point(aes(x=employee, y=time, fill=employee, color=employee, size=age)) #ROTATE 
```

```{r bobs3d, warning=F, message=F}
  ggplot(burgers) + 
    geom_point(aes(x=employee, y=time, fill=employee, color=employee, size=age)) 
```

```{r bobs4a, warning=F, message=F}
  ggplot(burgers) + 
    geom_col(aes(x=time, y=employee), stat="identity") 

```


```{r bobs4b, warning=F, message=F}
  ggplot(burgers) + 
    geom_col(aes(x=time, y=employee), stat="identity")

```

---

```{r disney}
disney <- read_csv("../slides_data/disney_movies_total_gross.csv")

glimpse(disney)
```


```{r adjust}
disney <- disney |> 
  mutate(release_date=mdy(release_date),
         total_gross=parse_number(total_gross),
         inflation_adjusted_gross=parse_number(inflation_adjusted_gross)) 

glimpse(disney)
```
---

```{r disney3, warning=F, message=F}
disney |> 
  ggplot(aes(x=release_date, 
             y=inflation_adjusted_gross,
             color=genre)) +
  geom_point() 
```


```{r disney4, warning=F, message=F}
disney |> 
  ggplot(aes(x=release_date, 
             y=inflation_adjusted_gross, 
             color=genre)) +
  geom_point() +
  scale_x_date(limits=c(ymd("1980-01-01"), ymd("2020-01-01")))
```


```{r disney5, warning=F, message=F}
disney |> 
  ggplot(aes(x=release_date, 
             y=inflation_adjusted_gross, 
             color=genre)) +
  geom_point() +
  scale_x_date(limits=c(ymd("1980-01-01"), 
                              ymd("2020-01-01"))) +
  scale_y_continuous(limits=c(0, 1000000000)) 

```


```{r disney6, warning=F, message=F}
disney |> 
  ggplot(aes(x=release_date, 
             y=inflation_adjusted_gross, 
             color=genre)) +
  geom_point() +
  scale_x_date(limits=c(ymd("1980-01-01"), 
                              ymd("2020-01-01")),
                     labels=scales::date_format("%Y")) +
  scale_y_continuous(limits=c(0, 1000000000),
                     labels=scales::dollar_format()) 

```


```{r disney7, warning=F, message=F}
disney |> 
  ggplot(aes(x=release_date, 
             y=inflation_adjusted_gross)) +
  geom_point() +
  scale_x_date(limits=c(ymd("1980-01-01"), 
                              ymd("2020-01-01")),
                     labels=scales::date_format("%Y")) +
  scale_y_continuous(limits=c(0, 1000000000),
                     labels=scales::dollar_format()) +
  facet_wrap(~genre)

```


```{r disney7a, warning=F, message=F}
disney |> 
  ggplot(aes(x=release_date, 
             y=inflation_adjusted_gross)) +
  geom_point() +
  scale_x_date(limits=c(ymd("1980-01-01"), 
                              ymd("2020-01-01")),
                     labels=scales::date_format("%Y")) +
  scale_y_continuous(limits=c(0, 1000000000),
                     labels=scales::dollar_format()) +
  facet_wrap(~genre) +
  labs(title="Disney animated movie gross profit") +
  labs(subtitle="Adjusted for inflation") +
  labs(y="", x="") +
  labs(caption="Data: Source Goes Here")

```


```{r disney8, warning=F, message=F}
disney |> 
  ggplot(aes(x=release_date, 
             y=inflation_adjusted_gross)) +
  geom_point() +
  scale_x_date(limits=c(ymd("1980-01-01"), 
                              ymd("2020-01-01")),
                     labels=scales::date_format("%Y")) +
  scale_y_continuous(limits=c(0, 1000000000),
                     labels=scales::dollar_format()) +
  facet_wrap(~genre) +
  labs(title="Disney animated movie gross profit") +
  labs(subtitle="Adjusted for inflation") +
  labs(y="", x="") +
  labs(caption="Data: Source Goes Here") +
  theme(strip.background = element_rect(colour = "black", fill = "white")) +
  theme(legend.key = element_rect(fill = "white", colour = "black")) +
  theme_minimal()
```
---


